language: scala
scala:
  - "2.10.2"
branches:
  only:
    - master
jdk:
  - oraclejdk7
  - openjdk7
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION publish-signed
services:
  - cassandra